export const createProjectStyles = {
	rolesList: {
		display: "flex",
		flexDirection: "column",
		gap: "1rem",
		marginTop: "0.5rem",
	},
	roleCard: {
		border: "1px solid #e6eefc",
		borderRadius: 8,
		padding: "0.75rem",
		background: "white",
	},
	removeRoleButton: {
		background: "transparent",
		border: "none",
		color: "#ff6b6b",
		cursor: "pointer",
	},
	compChip: {
		background: "#f0f8ff",
		border: "1px solid #1e90ff",
		color: "#1e90ff",
		padding: "0.25rem 0.5rem",
		borderRadius: 6,
		display: "flex",
		alignItems: "center",
		gap: "0.4rem",
	},
	compRemoveButton: {
		background: "transparent",
		border: "none",
		cursor: "pointer",
		color: "#1e90ff",
		fontWeight: 700,
	},
	createButton: {
		backgroundColor: "#1890ff",
		color: "white",
		padding: "0.8rem 1.2rem",
		border: "none",
		borderRadius: 6,
		cursor: "pointer",
		fontSize: "1rem",
		minWidth: "140px",
	},
	cancelButton: {
		backgroundColor: "#ff4d4f",
		color: "white",
		padding: "0.8rem 1.2rem",
		border: "none",
		borderRadius: 6,
		cursor: "pointer",
		fontSize: "1rem",
		minWidth: "140px",
	},
	rolesContainer: {
		display: "flex",
		flexDirection: "column",
		gap: "0.5rem",
		marginBottom: "1.5rem",
		marginTop: "1.5rem",
	},
	roleChip: {
		background: "#e8f6ff",
		border: "1px solid #bfe6ff",
		color: "#033b6b",
		padding: "0.25rem 0.5rem",
		borderRadius: 6,
		fontSize: "1.2rem",
		display: "flex",
		alignItems: "center",
		marginRight: "0.4rem",
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
	},
	roleName: {
		fontSize: "1.8rem",
		color: "#1e90ff",
		cursor: "pointer",
	},
};
