export const projectPageStyles = {
	card: {
		border: "2px solid #e0e0e0",
		backgroundColor: "white",
		padding: "2rem",
		borderRadius: "10px",
		boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
		width: "100%",
		boxSizing: "border-box",
	},
	header: {
		display: "flex",
		justifyContent: "space-between",
		alignItems: "baseline",
		gap: "1rem",
	},
	title: {
		color: "#1e90ff",
		fontSize: "2rem",
		margin: 0,
	},
	meta: {
		fontSize: "0.95rem",
	},
	countTitle: {
		margin: "0.5rem 0 0 auto",
		fontSize: "1.2rem",
		marginTop: 10,
		marginRight: "auto",
		textAlign: "center",
	},
	statusBadge: {
		padding: "0.25rem 0.6rem",
		borderRadius: 6,
		textTransform: "capitalize",
		textAlign: "center",
		fontSize: "1.5rem",
	},
	description: {
		margin: "0.5rem 0 1rem 0",
		fontSize: "1.4rem",
	},
	rolesList: {
		marginTop: "1.5rem",
		display: "flex",
		flexDirection: "column",
		gap: "0.75rem",
	},
	roleRow: {
		background: "white",
		border: "1px solid #e0e0e0",
		padding: "0.75rem",
		borderRadius: 8,
	},
	roleHeader: {
		display: "flex",
		alignItems: "center",
		gap: "1rem",
	},
	roleName: {
		fontSize: "1.8rem",
		color: "#1e90ff",
		cursor: "pointer",
	},
	roleQuantity: {
		fontSize: "1.2rem",
		marginLeft: "auto",
	},
	roleDescription: {
		fontSize: "1.4rem",
		marginTop: "0.5rem",
	},
	competencesList: {
		marginTop: "1rem",
		display: "flex",
		gap: "0.5rem",
		flexWrap: "wrap",
	},
	competenceChip: {
		background: "#e8f6ff",
		border: "1px solid #bfe6ff",
		color: "#033b6b",
		padding: "0.25rem 0.5rem",
		borderRadius: 6,
		fontSize: "1.2rem",
		display: "flex",
		alignItems: "center",
		marginRight: "0.4rem",
	},

	applicationName: {
		color: "#1e90ff",
		margin: "0 0 0.5rem 0",
		fontSize: "1.8rem",
		textAlign: "center",
	},
	projectRoleName: {
		fontSize: "1.5rem",
	},
	selectedRolesContainer: {
		display: "flex",
		flexDirection: "column",
		gap: "0.5rem",
		marginTop: "1.5rem",
		marginBottom: "1.5rem",
	},
	availableRolesContainer: {
		display: "flex",
		flexDirection: "column",
		gap: "0.5rem",
		marginTop: "1.5rem",
		marginBottom: "1.5rem",
	},
	controlsRow: {
		marginTop: "1rem",
		display: "flex",
		gap: "0.5rem",
		alignItems: "center",
	},
	buttonsRow: {
		alignItems: "center",
		display: "flex",
		justifyContent: "center",
		gap: "1rem",
		marginTop: 8,
	},
	button: {
		backgroundColor: "#1e90ff",
		color: "white",
		padding: "0.6rem 1rem",
		border: "none",
		borderRadius: 6,
		cursor: "pointer",
		fontSize: "1.2rem",
	},
	startButton: {
		marginTop: "1.2rem",
		backgroundColor: "#1e90ff",
		color: "white",
		padding: "0.6rem 1rem",
		border: "none",
		borderRadius: 6,
		cursor: "pointer",
		fontSize: "1.2rem",
	},
	buttonDanger: {
		backgroundColor: "#ff6b6b",
		color: "white",
		padding: "0.6rem 1rem",
		border: "none",
		borderRadius: 6,
		cursor: "pointer",
		fontSize: "1.2rem",
	},
	prioritySelect: {
		padding: "0.4rem",
		borderRadius: 6,
		border: "1px solid #e0e0e0",
	},
	cancelButton: {
		marginLeft: 8,
		padding: "0.6rem 1rem",
		borderRadius: 6,
		border: "1px solid #e0e0e0",
		background: "white",
		color: "#333",
		cursor: "pointer",
	},
};
