export const searchStyles = {
	nameInput: {
		width: "100%",
	},
	filtersRow: {
		display: "flex",
		gap: "1rem",
		marginBottom: "1rem",
	},
	chipContainer: {
		display: "flex",
		gap: "0.5rem",
		marginTop: "0.5rem",
		flexWrap: "wrap",
	},
	chip: {
		background: "#f0f8ff",
		border: "1px solid #1e90ff",
		color: "#1e90ff",
		padding: "0.25rem 0.5rem",
		borderRadius: 6,
		fontSize: "1.2rem",
		display: "flex",
		alignItems: "center",
		gap: "0.4rem",
		marginTop: "0.4rem",
		marginRight: "0.4rem",
	},
	chipRemoveButton: {
		background: "transparent",
		border: "none",
		cursor: "pointer",
		color: "#1e90ff",
		fontWeight: 700,
	},
	results: {
		marginTop: "1.5rem",
		display: "flex",
		flexDirection: "column",
		gap: "1rem",
	},
	paginationContainer: {
		display: "flex",
		justifyContent: "center",
		marginTop: "1rem",
	},
	paginationInner: {
		display: "flex",
		alignItems: "center",
		gap: "1rem",
	},
	paginationButton: {
		backgroundColor: "#1e90ff",
		color: "white",
		padding: "0.6rem 1rem",
		border: "none",
		borderRadius: 5,
		cursor: "pointer",
		fontSize: "1rem",
	},
	paginationButtonDisabled: {
		backgroundColor: "#d0eaff",
		color: "white",
		padding: "0.6rem 1rem",
		border: "none",
		borderRadius: 5,
		cursor: "not-allowed",
		fontSize: "1rem",
	},
	pageTitle: {
		color: "#1e90ff",
		fontSize: "1.25rem",
		fontWeight: 600,
	},
	highlightRoleBg: "#b6e8ff",
	highlightRoleBorder: "#7fd7ff",
};
