export const userCompetenceStyles = {
	container: {
		display: "flex",
		flexDirection: "column",
		gap: "1rem",
	},
	searchRow: {
		marginBottom: "1rem",
	},
	competenceList: {
		display: "flex",
		gap: "0.75rem",
		flexWrap: "wrap",
	},
	competenceChip: {
		background: "#e8f6ff",
		border: "1px solid #bfe6ff",
		color: "#033b6b",
		padding: "0.5rem 0.75rem",
		borderRadius: 8,
		fontSize: "1.2rem",
		display: "flex",
		alignItems: "center",
		gap: "0.5rem",
	},
	removeButton: {
		background: "transparent",
		border: "none",
		cursor: "pointer",
		color: "#1e90ff",
		fontWeight: 700,
		fontSize: "1.1rem",
	},
	emptyText: {
		color: "#666",
		fontSize: "1rem",
	},
	levels: {
		1: { bg: "#e8f6ff", border: "#bfe6ff", text: "#033b6b" },
		2: { bg: "#cfefff", border: "#9fe0ff", text: "#022f57" },
		3: { bg: "#b6e8ff", border: "#7fd7ff", text: "#01283f" },
	},
	levelSelector: {
		fontSize: "1.2rem",
		display: "flex",
		gap: "0.5rem",
		alignItems: "center",
		marginTop: "1rem",
	},
	levelButton: {
		fontSize: "1rem",
		padding: "0.4rem 0.6rem",
		borderRadius: 6,
		border: "none",
		background: "white",
		cursor: "pointer",
	},
	levelButtonActive: {
		fontSize: "1rem",
		background: "#1e90ff",
		color: "white",
		padding: "0.4rem 0.6rem",
		borderRadius: 6,
		border: "1px solid #1e90ff",
	},
	addConfirmButton: {
		fontSize: "1rem",
		marginLeft: "1rem",
		padding: "0.4rem 0.6rem",
		borderRadius: 6,
		border: "none",
		background: "#1e90ff",
		color: "white",
		cursor: "pointer",
	},
	addCancelButton: {
		padding: "0.4rem 0.6rem",
		fontSize: "1rem",
		borderRadius: 6,
		marginLeft: 8,
		background: "transparent",
		cursor: "pointer",
		border: "none",
	},
};
