"""add_org_to_proj

Revision ID: 03b0e82239a3
Revises: 4f499be456a5
Create Date: 2026-04-05 23:54:24.678721

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "03b0e82239a3"
down_revision: Union[str, None] = "4f499be456a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
