"""user_role

Revision ID: 1b389c05edfd
Revises: 9253978e92db
Create Date: 2026-04-11 02:52:40.267603

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1b389c05edfd"
down_revision: Union[str, None] = "9253978e92db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_competences", "user_competences", ["user_id", "competence_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_competences", "user_competences", type_="unique")
    # ### end Alembic commands ###
