"""user_competence

Revision ID: 30f80d630e38
Revises: c58a00d86539
Create Date: 2026-04-08 04:51:48.133733

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "30f80d630e38"
down_revision: Union[str, None] = "c58a00d86539"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
