"""add_org_to_proj

Revision ID: 4f499be456a5
Revises: b287d5f106eb
Create Date: 2026-04-05 17:39:51.169026

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "4f499be456a5"
down_revision: Union[str, None] = "b287d5f106eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
