"""user_competence

Revision ID: 5b0b0cb330de
Revises: be0f4eb963a7
Create Date: 2026-04-06 06:05:30.653279

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "5b0b0cb330de"
down_revision: Union[str, None] = "be0f4eb963a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
