"""user_role

Revision ID: 64de0826c023
Revises: 579d506f80a7
Create Date: 2026-04-10 06:23:49.238377

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "64de0826c023"
down_revision: Union[str, None] = "579d506f80a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
