"""user_role

Revision ID: 65bb4d2443ba
Revises: 1b389c05edfd
Create Date: 2026-04-16 04:29:39.746225

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "65bb4d2443ba"
down_revision: Union[str, None] = "1b389c05edfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
