"""user_competence

Revision ID: 7518b74cd736
Revises: e71a4e68bceb
Create Date: 2026-04-08 05:52:59.977923

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7518b74cd736"
down_revision: Union[str, None] = "e71a4e68bceb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
