"""add_user_table

Revision ID: 8ddb683dd904
Revises:
Create Date: 2026-03-17 06:02:14.103555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pandas as pd
import os

# revision identifiers, used by Alembic.
revision: str = "8ddb683dd904"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    users_df = pd.read_csv(os.getcwd() + "/migration/synthetic_data/users.csv")
    users_df["patronymic"] = None
    users_df = users_df[
        ["first_name", "surname", "patronymic", "email", "hash_password", "role"]
    ]
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(always=False, start=1, increment=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("user", "organizer", name="userroletype"),
            server_default="user",
            nullable=False,
        ),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("patronymic", sa.String(length=50), nullable=True),
        sa.Column("surname", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hash_password", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.bulk_insert(users_table, users_df.to_dict("records"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
