"""user_role

Revision ID: 9253978e92db
Revises: f6cecfb24517
Create Date: 2026-04-11 02:51:18.210333

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9253978e92db"
down_revision: Union[str, None] = "f6cecfb24517"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_project_users", "project_users", ["user_id", "project_role_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_project_users", "project_users", type_="unique")
    # ### end Alembic commands ###
