"""add_org_to_proj

Revision ID: 9598ba8b55b3
Revises: 7d190309198a
Create Date: 2026-04-05 17:00:51.376672

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9598ba8b55b3"
down_revision: Union[str, None] = "7d190309198a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_projects_roles_role_id", "project_roles", ["role_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_projects_roles_role_id", table_name="project_roles")
    # ### end Alembic commands ###
