"""add_org_to_proj

Revision ID: b287d5f106eb
Revises: ebd6f778b6a1
Create Date: 2026-04-05 17:12:44.326523

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "b287d5f106eb"
down_revision: Union[str, None] = "ebd6f778b6a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
