"""user_role

Revision ID: b709d05ca581
Revises: be4f7962a6c2
Create Date: 2026-04-16 06:37:08.670210

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b709d05ca581"
down_revision: Union[str, None] = "be4f7962a6c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
