"""add_org_to_proj

Revision ID: be0f4eb963a7
Revises: 03b0e82239a3
Create Date: 2026-04-06 05:46:31.559682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "be0f4eb963a7"
down_revision: Union[str, None] = "03b0e82239a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_projects_search"), table_name="projects", postgresql_using="gin"
    )
    op.drop_column("projects", "search_vector")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('russian'::regconfig, (((COALESCE(name, ''::character varying))::text || ' '::text) || COALESCE(description, ''::text)))",
                persisted=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_projects_search"),
        "projects",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
