"""user_role

Revision ID: c39af6482708
Revises: 7f8c44494966
Create Date: 2026-04-16 06:25:43.413878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39af6482708'
down_revision: Union[str, None] = '7f8c44494966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('competence_match', sa.Float(), nullable=False))
    op.add_column('team_members', sa.Column('role_score', sa.Float(), nullable=False))
    op.drop_column('team_members', 'score')
    op.drop_column('teams', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('team_members', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('team_members', 'role_score')
    op.drop_column('team_members', 'competence_match')
    # ### end Alembic commands ###
