"""user_competence

Revision ID: c58a00d86539
Revises: 6aec9fb1a73f
Create Date: 2026-04-08 04:50:13.732596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c58a00d86539"
down_revision: Union[str, None] = "6aec9fb1a73f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_competences", sa.Column("competence_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(op.f("uq_user_competence"), "user_competences", type_="unique")
    op.create_unique_constraint(
        "uq_user_competence", "user_competences", ["user_id", "competence_id"]
    )
    op.drop_constraint(
        op.f("user_competences_cometence_id_fkey"),
        "user_competences",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "user_competences",
        "competences",
        ["competence_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("user_competences", "cometence_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_competences",
        sa.Column("cometence_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user_competences", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_competences_cometence_id_fkey"),
        "user_competences",
        "competences",
        ["cometence_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_user_competence", "user_competences", type_="unique")
    op.create_unique_constraint(
        op.f("uq_user_competence"),
        "user_competences",
        ["user_id", "cometence_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("user_competences", "competence_id")
    # ### end Alembic commands ###
