"""user_role

Revision ID: ceaac4a4095d
Revises: 8f86aef6db69
Create Date: 2026-04-16 07:23:50.902513

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "ceaac4a4095d"
down_revision: Union[str, None] = "8f86aef6db69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
