"""user_role

Revision ID: dce64a95fbe8
Revises: 2f752a512d4a
Create Date: 2026-04-16 06:38:38.209301

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "dce64a95fbe8"
down_revision: Union[str, None] = "2f752a512d4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
