"""user_competence

Revision ID: e71a4e68bceb
Revises: 30f80d630e38
Create Date: 2026-04-08 04:57:32.191643

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e71a4e68bceb"
down_revision: Union[str, None] = "30f80d630e38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
