"""add_org_to_proj

Revision ID: ebd6f778b6a1
Revises: 9598ba8b55b3
Create Date: 2026-04-05 17:06:42.288379

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "ebd6f778b6a1"
down_revision: Union[str, None] = "9598ba8b55b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
