"""synth_users

Revision ID: ec7ed70bf21f
Revises: ed9b02fdc2e6
Create Date: 2026-04-19 17:32:35.414357

"""

from typing import Sequence, Union

from alembic import op
from core.models.postgres import (
    UserCompetenceAssociationDB,
    UserProjectRoleAssociationDB,
)
import pandas as pd

# revision identifiers, used by Alembic.
revision: str = "ec7ed70bf21f"
down_revision: Union[str, None] = "ed9b02fdc2e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        UserCompetenceAssociationDB.__table__,
        pd.read_csv("./migration/synthetic_data/user_competence.csv").to_dict(
            "records"
        ),
    )
    op.bulk_insert(
        UserProjectRoleAssociationDB.__table__,
        pd.read_csv("./migration/synthetic_data/user_project_role.csv").to_dict(
            "records"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
