"""synth_project

Revision ID: ed9b02fdc2e6
Revises: 8e4b7e600590
Create Date: 2026-04-19 16:45:55.569362

"""

from typing import Sequence, Union

from alembic import op
import pandas as pd
from core.models.postgres import (
    UserDB,
    RoleDB,
    CompetenceDB,
    ProjectDB,
    ProjectRoleAssociationDB,
    ProjectRoleCompetenceAssociationDB,
)

# revision identifiers, used by Alembic.
revision: str = "ed9b02fdc2e6"
down_revision: Union[str, None] = "8e4b7e600590"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    project_df = pd.read_csv("./migration/synthetic_data/project.csv")
    project_df["start_time"] = pd.to_datetime(project_df["start_time"])

    op.bulk_insert(
        UserDB.__table__,
        pd.read_csv("./migration/synthetic_data/users.csv")
        .drop(["id"], axis=1)
        .to_dict("records"),
    )
    op.bulk_insert(
        RoleDB.__table__,
        pd.read_csv("./migration/synthetic_data/roles.csv")
        .drop(["id"], axis=1)
        .to_dict("records"),
    )
    op.bulk_insert(
        CompetenceDB.__table__,
        pd.read_csv("./migration/synthetic_data/competences.csv")
        .drop(["id"], axis=1)
        .to_dict("records"),
    )
    op.bulk_insert(
        ProjectDB.__table__, project_df.drop(["id"], axis=1).to_dict("records")
    )
    op.bulk_insert(
        ProjectRoleAssociationDB.__table__,
        pd.read_csv("./migration/synthetic_data/project_role.csv")
        .drop(["id"], axis=1)
        .to_dict("records"),
    )
    op.bulk_insert(
        ProjectRoleCompetenceAssociationDB.__table__,
        pd.read_csv("./migration/synthetic_data/project_role_competence.csv").to_dict(
            "records"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
