"""user_role

Revision ID: f6cecfb24517
Revises: 64de0826c023
Create Date: 2026-04-11 01:11:06.473247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6cecfb24517"
down_revision: Union[str, None] = "64de0826c023"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_roles",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "project_roles",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "project_users",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "project_users",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.drop_constraint(
        op.f("uq_user_project_roles_priority"), "project_users", type_="unique"
    )
    op.create_index(
        "ix_project_users_project_role_id",
        "project_users",
        ["project_role_id"],
        unique=False,
    )
    op.drop_column("project_users", "id")
    op.alter_column(
        "projects",
        "status",
        existing_type=postgresql.ENUM(
            "RECRUITING", "CANCELLED", "COMPLETED", name="projectstatus"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.add_column(
        "role_competences",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "role_competences",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.alter_column(
        "role_competences",
        "importance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.create_index(
        "ix_role_competences_competence_id",
        "role_competences",
        ["competence_id"],
        unique=False,
    )
    op.add_column(
        "user_competences",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "user_competences",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.drop_constraint(op.f("uq_user_competence"), "user_competences", type_="unique")
    op.create_index(
        "ix_user_competences_competence_id",
        "user_competences",
        ["competence_id"],
        unique=False,
    )
    op.drop_column("user_competences", "id")
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("user", "organizer", name="userroletype"),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'user'::userroletype"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(),
        type_=postgresql.ENUM("user", "organizer", name="userroletype"),
        existing_nullable=False,
        existing_server_default=sa.text("'user'::userroletype"),
    )
    op.add_column(
        "user_competences",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=2147483647,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
    )
    op.drop_index("ix_user_competences_competence_id", table_name="user_competences")
    op.create_unique_constraint(
        op.f("uq_user_competence"),
        "user_competences",
        ["user_id", "competence_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("user_competences", "updated_at")
    op.drop_column("user_competences", "created_at")
    op.drop_index("ix_role_competences_competence_id", table_name="role_competences")
    op.alter_column(
        "role_competences",
        "importance",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_column("role_competences", "updated_at")
    op.drop_column("role_competences", "created_at")
    op.alter_column(
        "projects",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "RECRUITING", "CANCELLED", "COMPLETED", name="projectstatus"
        ),
        existing_nullable=False,
    )
    op.add_column(
        "project_users",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=2147483647,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
    )
    op.drop_index("ix_project_users_project_role_id", table_name="project_users")
    op.create_unique_constraint(
        op.f("uq_user_project_roles_priority"),
        "project_users",
        ["user_id", "project_role_id", "priority"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("project_users", "updated_at")
    op.drop_column("project_users", "created_at")
    op.drop_column("project_roles", "updated_at")
    op.drop_column("project_roles", "created_at")
    # ### end Alembic commands ###
